### ISSUE TITLE
Updated manuscript: How are `pathology_free_text_diagnosis` and pathology_diagnosis` being used?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-manuscript#123]
#### What section of the manuscript should be updated?

The clinical-data-harmonization section: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#clinical-data-harmonization 

and the molecular subtyping section: https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#molecular-subtyping

#### Proposed changes

Two things would be helpful: 

- I'm suspecting that the `Notes` column might be the same `pathology_free_text_diagnosis` is this true? If yes, can that be added or explained? If it isn't, can we add an explanation about `pathology_free_text_diagnosis` to that table?

-  In the `molecular-subtyping`, can we add one sentence that specifies what variable is being used for molecular subtyping? I think based on the series of issues filed in OpenPBTA-analysis, this would be `pathology_diagnosis` now, but those issues also mention something about searching for samples using `pathology_free_text_diagnosis`? 

I'm a bit confused on how `pathology_free_text_diagnosis` should be used in analyses - or is it only for record keeping? But this may be a question for over on OpenPBTA-analysis

**Comment by jharenza** [comment]
> * I'm suspecting that the `Notes` column might be the same `pathology_free_text_diagnosis` is this true? If yes, can that be added or explained? If it isn't, can we add an explanation about `pathology_free_text_diagnosis` to that table?
> *

These are not the same. `Notes` was meant for tracking when/how we got from `pathology_diagnosis` to `integrated_diagnosis`, if there was a change. I tracked an issue [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/607) to update this to be a bit more informative, but still on the list of to-dos. Also, thanks for adding this ticket )(also on my to-dos) - YES, we do have to add `pathology_free_text_diagnosis` to the harmonization table, and as well, have to update logic for `CNS_region`, per #106. Someone at D3b will take care of those.

> *In the molecular-subtyping, can we add one sentence that specifies what variable is being used for molecular subtyping? I think based on the series of issues filed in OpenPBTA-analysis, this would be pathology_diagnosis now, but those issues also mention something about searching for samples using pathology_free_text_diagnosis?
> *

Sure - as background, I created [this ticket](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/748) to explain the new way the `pbta-histologies.tsv` file is being created. With V17, we could not implement all SQL rules because the subtyping is currently done as follows:

| molecular subtyping module | variable being used  |
|----------------------------|----------------------|
| LGAT                       | short_histology      |
| HGG                        | short_histology      |
| embryonal                  | broad_histology      |
| EPN                        | integrated_diagnosis |
| EWS                        | short_histology      |
| MB                         | integrated_diagnosis |

However, I hesitate adding this to the methods, since we will replace _**all**_ of these with use of `pathology_diagnosis` and `pathology_free_text_diagnosis`, which I expect to happen with V18. But, I agree this should be documented somewhere -- perhaps in the `data-formats.md` file, which looks like it is a bit out of date re: subtyping anyway? Thoughts, @jaclyn-taroni?

Re:`pathology_free_text_diagnosis` and searching - we added this because during the clinical data refresh, some samples which previously had a `pathology_diagnosis` of a specific cancer were updated to `Other`, and some of those were previously subtyped (see table below). If `pathology_diagnosis` == `Other`, then we should search `pathology_free_text_diagnosis` to determine whether a sample fits that cohort for subtyping (most relevant to embryonal tumors).

| Kids_First_Biospecimen_ID | pathology_diagnosis | pathology_free_text_diagnosis                                |
|---------------------------|---------------------|--------------------------------------------------------------|
| BS_QB7YGKN1               | Other               | glioneuronal tumor                                           |
| BS_2Z9JQDPV               | Other               | non- langerhans histiocytosis (jxg- cns)                     |
| BS_F5BZSF3Q               | Other               | inclusion cyst                                               |
| BS_02W5H7K5               | Other               | rosai-dorfman disease                                        |
| BS_FEPRNEXX               | Other               | ependymoblastoma                                             |
| BS_MGY2V5N4               | Other               | neuroepithelial neoplasm                                     |
| BS_F6V1Y4QS               | Other               | neuroepithelial neoplasm                                     |
| BS_BM95DGCQ               | Other               | prolactinoma                                                 |
| BS_8WPNFT03               | Other               | non- langerhans histiocytosis (jxg- cns)                     |
| BS_VQEPFE1P               | Other               | meningioangiomatosis                                         |
| BS_06XH7EVF               | Other               | osteoblastoma                                                |
| BS_R1RMKH1B               | Other               | ganglioneuroma                                               |
| BS_B61168DE               | Other               | malignant melanocytic neoplasm                               |
| BS_8D52JK1Q               | Other               | malignant melanocytic neoplasm                               |
| BS_JSPR854S               | Other               | perineuroma                                                  |
| BS_CXN0498B               | Other               | osteoblastoma                                                |
| BS_5KK9P7XD               | Other               | meningioangiomatosis                                         |
| BS_MS87PMR7               | Other               | rathke cleft cyst                                            |
| BS_W6AC5J3C               | Other               | meningioangiomatosis                                         |
| BS_9R82A3VT               | Other               | dermoid cyst                                                 |
| BS_Z72QAZC7               | Other               | dermoid cyst                                                 |
| BS_8Q8CAY84               | Other               | hamartoma                                                    |
| BS_QBR4WCQ2               | Other               | myxoid spindle cell tumor                                    |
| BS_AHT9PKVE               | Other               | embryonal tumor, nos, congenital type                        |
| BS_3ZASRA3A               | Other               | epidermoid cyst                                              |
| BS_1135HC0V               | Other               | cortical tubers                                              |
| BS_BVD7PWP5               | Other               | choroid plexus cyst                                          |
| BS_9G69F50J               | Other               | ossifying fibroma                                            |
| BS_NDFDQBCZ               | Other               | myofibroblastic tumor                                        |
| BS_BS5X4H0Y               | Other               | dermoid inclusion cyst                                       |
| BS_4Z6F1HJZ               | Other               | myxoid spindle cell tumor                                    |
| BS_HCP5C912               | Other               | meningioangiomatosis                                         |
| BS_H83DTMT2               | Other               | dermoid cyst                                                 |
| BS_Z4S81HG1               | Other               | myofibroblastic tumor                                        |
| BS_886M7JMG               | Other               | arteriovenous malformation                                   |
| BS_69VS8PS1               | Other               | embryonal tumor with multilayer rosettes, ros (who grade iv) |
| BS_MCM78YPC               | Other               | reactive connective tissue                                   |
| BS_Q807ENGY               | Other               | perineuroma                                                  |
| BS_W50WEJE7               | Other               | ossifying fibroma                                            |
| BS_9XWJ88Q1               | Other               | osteoblastoma                                                |
| BS_37GTVG4N               | Other               | embryonal tumor with multilayer rosettes, ros (who grade iv) |
| BS_XKXDH0YJ               | Other               | atypical lymphoid infiltrate                                 |
| BS_Z7G68ZS2               | Other               | atypical lymphoid infiltrate                                 |
| BS_AA164D3A               | Other               | dermoid cyst                                                 |
| BS_1T19NFJ8               | Other               | epilepsy, chronic rasmussen encephalitis                     |
| BS_KK0JWATQ               | Other               | reactive connective tissue                                   |
| BS_N5VYY66W               | Other               | meningioangiomatosis                                         |
| BS_TPX7YY57               | Other               | epilepsy, chronic rasmussen encephalitis                     |
| BS_N9BF56FP               | Other               | fibromyxoid lesion                                           |
| BS_B8T7M0WV               | Other               | arteriovenous malformation                                   |
| BS_4XPPZTGG               | Other               | xanthogranuloma                                              |
| BS_0HW7W7SD               | Other               | medullooepithelioma                                          |
| BS_N9SMBR24               | Other               | fibroma                                                      |
| BS_49F4RAA4               | Other               | rosai-dorfman disease                                        |
| BS_B24PKKQB               | Other               | hamartoma                                                    |
| BS_6R7SFVV2               | Other               | ganglioneuroma                                               |
| BS_T1QMEH1N               | Other               | xanthogranuloma                                              |
| BS_V2MDX7HG               | Other               | inclusion cyst                                               |
| BS_AQMKA8NC               | Other               | ependymoblastoma                                             |
| BS_ZH1FBX50               | Other               | cortical tubers                                              |
| BS_F9WKPDFG               | Other               | choroid plexus cyst                                          |
| BS_DVCQ8XDZ               | Other               | meningioangiomatosis                                         |
| BS_947CK40E               | Other               | dermoid cyst                                                 |
| BS_92MT680S               | Other               | fibromyxoid lesion                                           |
| BS_32VQRFDS               | Other               | osteoblastoma                                                |
| BS_QZFEB94Q               | Other               | fibroma                                                      |
| BS_7BW0YRPY               | Other               | embryonal tumor, nos, congenital type                        |

**Comment by jharenza** [comment]
I am working on this today

**Comment by jharenza** [comment]
closed with #126
