### ISSUE TITLE
Updated manuscript: create release for this repo

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#191]
#### What section of the manuscript should be updated?

full

#### Proposed changes

create release of repo once ready for submission

#### Relevant literature

NA

**Comment by sjspielman** [comment]
@jaclyn-taroni @jharenza I want to note that this doesn't appear to have been done with the initial submission. Since we're going to be begin implementing response to review soon, if we still want to have a submission-specific release, we'd want to make it _now_ before new PRs with revisions get merged.

**Comment by jaclyn-taroni** [comment]
There were a few tweaks that were made for journal and preprint submission that should go in prior to cutting a release. I've sent @sjspielman a Word document associated with the preprint submission. The plan is to use the compare documents feature of Word to fin the differences between that version and the version on GitHub, file a PR with any changes, and then cut a release once that goes in.
