### ISSUE TITLE
Replace figure links

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#239]
Finalized-for-draft PNG figures are currently being made in https://github.com/AlexsLemonade/OpenPBTA-analysis.

When ready, the respective temporary PNGs in `content/images/main/` should be removed, and relative links to the respective figure should be replaced with links to the analysis repo PNGs.

Add a check when each update is merged in, and feel free to give a status update with the bullet.

- [ ] Figure 1. PR: #244 
- [ ] Figure 2 PR: #243 
- [ ] Figure 3
- [ ] Figure 4
- [ ] Figure 5
- [ ] Figure S1 PR: #244 
- [ ] Figure S2 PR: #244 
- [ ] Figure S3 PR: #244 but needs another update once https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1328 is merged - updating in #243 
- [ ] Figure S4 PR: #244 
- [ ] Figure S5 PR: #244 but needs another update once content is finalized - updating in #243

**Comment by jharenza** [comment]
Just noting that the figure 1 link isn't rendering. I tried to add a versioned link [here](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/244) per the [USAGE](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md) instructions, since these are no longer located in this repo.

>For images created by the manuscript authors that are hosted elsewhere on GitHub, we recommend using a [versioned](https://help.github.com/articles/getting-permanent-links-to-files/) GitHub URL to embed figures, thereby preserving exact image provenance. When embedding SVG images hosted on GitHub, it's necessary to append ?sanitize=true to the raw.githubusercontent.com URL. For example:
```
https://raw.githubusercontent.com/greenelab/scihub/572d6947cb958e797d1a07fdb273157ad9154273/figure/citescore.svg?sanitize=true
```

I am not sure why this isn't rendering using either method. If we cannot figure this out, the quickest and easiest solution is to copy them over to this repo - thoughts @jaclyn-taroni ?

**Comment by jaclyn-taroni** [comment]
Two things:

* Did you try the version of the URL that begins with `https://raw.githubusercontent.com/`? It did not look like that was included in the commits on #244, but I could be wrong.
* Is the method that you're using to determine that it is not working based on what is included in the AppVeyor HTML output or have you built locally? To me, it looks like figures that _do render_ in the HTML version linked as a badge in the main README also don't show up in the AppVeyor version (e.g., Figure 2), so that may not be a great test/indicator.

**Comment by jharenza** [comment]
For 1, I didn't try that yet because I read that as svg-specific but can try this afternoon for sure. For 2, I was using the appveyor pdf as an indicator.

**Comment by jharenza** [comment]
👍 for raw user content: https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/244/commits/248da51e44b1bfc17b793f41c7cb05b4b9b94125

Updating all figures now!

**Comment by jharenza** [comment]
All of the links are updated to date in #249, but once Figure S5 is re-generated, they will all need a new commit, so I just unchecked all of above
