### ISSUE TITLE
Discussion: LGG and HGG wording throughout manuscript

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#268]
This issue is meant to formally nail down LGG and HGG terminology throughout the manuscript. This has been intermittently discussed in a bunch of disparate comments, so this issue will serve as a the finalized reference for terminology here.

In our [palette file](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/palettes/broad_histology_cancer_group_palette.tsv), we have the follow terminology which is used across figures:

+ "Low-grade astrocytic tumor" is a **`broad_histology`** with the following `cancer_group` categories:
  + "Low-grade glioma astrocytoma"
  + "Ganglioglioma"
  + "Other"
  + Three additional cancer groups are forthcoming with v22 (pilocytic astrocytoma, pleomorphic xanthoastrocytoma, and subependymal giant cell astrocytoma)

+ "Diffuse astrocytic and oligodendroglial tumor" is a **`broad_histology`** with the following `cancer_group` categories:
  + "High-grade glioma astrocytoma"
       + _ALERT_ The manuscript text often refers this as "non-midline high-grade gliomas"
  + "Diffuse midline glioma"
  + "Diffuse intrinsic pontine glioma"
  + "Other"

We additionally have several _survival models_ which define LGG and HGG status:
1. The LGG grouping written as is **only** the `cancer_group` "low-grade glioma astrocytoma" [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b8a0b3e062b646b1cbcfb8486f302250510d75bc/analyses/survival-analysis/survival-analysis_immune.Rmd#L125-L131) and [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b8a0b3e062b646b1cbcfb8486f302250510d75bc/analyses/survival-analysis/survival-analysis_tp53_telomerase.Rmd#L131-L149).
2. The HGG grouping is written as **all** of the cancer groups within `broad_histology`  "Diffuse astrocytic and oligodendroglial tumor" [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b8a0b3e062b646b1cbcfb8486f302250510d75bc/analyses/survival-analysis/survival-analysis_subtypes.Rmd#L81-L102) and [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b8a0b3e062b646b1cbcfb8486f302250510d75bc/analyses/survival-analysis/survival-analysis_tp53_telomerase.Rmd#L131-L149).

### Proposed path forward

1. First let's confirm our survival models are coded up as intended, or whether either/both...
    + The HGG group should have been more _narrow_ to a subset of cancer groups
    + The LGG group should have been the _entire_ broad histology instead of just that single cancer group

3. A lot of my confusion comes from the fact that we aren't actually using any terms that directly match the LGG and HGG acronyms, e.g. "low-grade glioma" and "high-grade glioma" are not terms we use. I therefore propose we update the **`broad_histology_display`** column in the palette file and actually use these terms for the broad histologies as they appear int the MS:
    + `Low-grade astrocytic tumor` --> `Low-grade glioma`
    + `Diffuse astrocytic and oligodendroglial tumor` --> `High-grade glioma`

4. We update the **`cancer_group_display`** column in the palette file for "High-grade glioma astrocytoma" and change to "Non-midline high-grade glioma"

Tagging @jharenza for discussion

**Comment by jharenza** [comment]
Thanks for starting this @sjspielman, but two updates on the above:
>The LGG grouping written as is only the cancer_group "low-grade glioma astrocytoma" [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b8a0b3e062b646b1cbcfb8486f302250510d75bc/analyses/survival-analysis/survival-analysis_immune.Rmd#L125-L131) and [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b8a0b3e062b646b1cbcfb8486f302250510d75bc/analyses/survival-analysis/survival-analysis_tp53_telomerase.Rmd#L131-L149).

This is not entirely true. General references to LGG in text are using a bucket term, and we need to update survival as you mention, because I didn't catch that some of this was starting to break out into cancer groups but wasn't completed.

>We update the cancer_group_display column in the palette file for "High-grade glioma astrocytoma" and change to "Non-midline high-grade glioma"

This may not always true, either. After thinking about this some more, we probably shouldn't refer to it this way because we didn't use the midline CNS region to determine what goes into "High-grade glioma astrocytoma" - it was basically everything leftover, which may include midline gliomas, but one thing in common is that they are all H3 wildtype if they had subtyping completed. The `DIPG` cancer group is likely a mix of H3+/- tumors because we only have RNA-Seq in this repo (had not aded the WGS as we cut off the data at a certain point).

>I therefore propose we update the broad_histology_display column in the palette file and actually use these terms for the broad histologies as they appear int the MS:
>Low-grade astrocytic tumor --> Low-grade glioma
>Diffuse astrocytic and oligodendroglial tumor --> High-grade glioma

I think we should definitely do this, since we are using "LGG/HGG" instead of "LGAT/HGAT" as our abbreviations.

I would probably suggest, if changing these now, to change `cancer_group_display` column in the palette file for "High-grade glioma astrocytoma" to "Non-classified HGG" or "Other HGG" and likewise same with "Low-grade glioma astrocytoma". These are definitely going to be a combination of tumors which have cancer group annotations - for eg, there may very well be JXAs/SEGAs in the "Other LGG" group" - this is because the way the data is collected, we only have a finite set of diagnoses and some of the more fine-grained dx are written in free text and those are then pulled out in `molecular-subtyping-pathology`. 

Another caveat that was shared by clinician Cassie Kline early on was that we don't want to analyze SEGA with the other LGGs. They were still subtyped within the LGG module because they are low grade gliomas, but they are pretty biologically different from my understanding. I imagine that we will still lump them for survival and thus use the `short_histology == "LGAT` field, rather than rely on `cancer_group`, but for any other analyses, break them out. 

So, I am not sure - what are your thoughts?

**Comment by sjspielman** [comment]
What I am drawing from this:

1. Survival analyses for LGG either need to be redone with ALL of the broad histology groupings, or figures need to be updated with a different label that more precisely reflects the grouping performed. The latter may be preferable if we do not want to include SEGA in the survival?

2. `broad_histology_display` should be updated Low-grade astrocytic tumor --> Low-grade glioma and Diffuse astrocytic and oligodendroglial tumor --> High-grade glioma.

3. `cancer_group` should be updated  High-grade glioma astrocytoma --> "Other high-grade gliomas" and Low-grade glioma astrocytoma --> "Other low-grade gliomas"

**Comment by sjspielman** [comment]
@jharenza I'm still not 100% sure what the plan for survival is.
You had written - 
> This is not entirely true. General references to LGG in text are using a bucket term, and we need to update survival as you mention, because I didn't catch that some of this was starting to break out into cancer groups but wasn't completed.

and

> Another caveat that was shared by clinician Cassie Kline early on was that we don't want to analyze SEGA with the other LGGs. 


My reading of this is to redo LGG models with all LGG broad histology _except_ SEGA. Is my reading correct? If so I'll file an issue in analysis so we can follow up after SEGA gets properly incorporated.

In addition, are there other analyses that would need to be redone that exclude SEGA? If so we'd want issues for those too.

**Comment by jharenza** [comment]
@sjspielman for the survival analysis, the LGG group should contain ALL LGG from LGAT, including SEGA. This is because we are asking whether   we see an effect because of a good prognosis or because of the variable we are measuring.

For other modules, I think we have that all settled by making SEGA a cancer group, so they'll automatically come out. They should remain in the LGG oncoprint. Does that help?

**Comment by jharenza** [comment]
grepped for `LGAT` or `HGAT` and this appears to be completed.
