### ISSUE TITLE
Updated manuscript: Double check oncoprint Ns

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-manuscript#408]
#### What section of the manuscript should be updated?

Results section

#### Proposed changes

With the change in independent samples, we should re-check the oncoprint Ns and stats

**Comment by sjspielman** [comment]
I've gone through the oncoprint numbers as follows, where I've **bolded** changes we need to make:

### LGG
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L135 
- 140 is correct: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/oncoprint-landscape/tables/primary_only_lgat_oncoprint_summary_n.tsv (This file has no V23 diff; I confirmed again that we didn’t just miss the diff)
- **227 -> 226** https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/primary_only_sample_n_in_oncoprint.tsv
	

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L136
- From the figure, these numbers are still all correct https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/figures/pngs/figure2.png

### Embryonal 
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L141
- 95 is correct https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/primary_only_n_per_cancer_group.tsv

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L142
- **There are no ATRT _SMARCB1_ in the figure, and none of the ATRTs show _SMARCA4_ alterations in the figure**: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/figures/pngs/figure2.png
- **We do not display other embryonal tumors in figure 2 - update sentence**


### HGG

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L146

- **61 —> 63 HGGs** https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/primary_only_sample_n_in_oncoprint.tsv
- _TP53_  57% is correct, but **update to 36/63** .  For _H3F3A_: **update to 54%, 34/63**
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/diffuse-midline-glioma_oncoprint_alteration_counts.tsv
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/high-grade-glioma-astrocytoma_oncoprint_alteration_counts.tsv   



https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L147
- all of these genes are still in the figure. Ok.


### Other CNS
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L153
- there are still 60 EPN and 31 cranio-  https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/primary_only_n_per_cancer_group.tsv
- I think the_C11orf95::RELA_ fraction is still correct, based on figure  https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/figures/pngs/figure2.png
- cranio CTNNB1 is still 21/31
  - https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/craniopharyngioma_oncoprint_alteration_counts.tsv 
	

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L154
- meningioma is still 7/17, EPN is still 3/60, but **schwan is now 3/12 (new denominator)**
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/primary_only_n_per_cancer_group.tsv
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/meningioma_oncoprint_alteration_counts.tsv
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/ependymoma_oncoprint_alteration_counts.tsv
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/schwannoma_oncoprint_alteration_counts.tsv

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L155

- From count file, ERB: 3, YAP1: 2, KRAS:1, MAML2: 1
  - https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/ependymoma_oncoprint_alteration_counts.tsv
  - **I’d rephrase this sentence also to `and/or` instead of and, since these are not strictly co-occurring, BUT since _KRAS_ is not in the figure anymore so we might remove _KRAS_ and still say 6/60 since 6 is definitely correct from the PNG** https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/figures/pngs/figure2.png

https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/789f65de824dcc28688d2751c0978bc6f86cb805/content/03.results.md?plain=1#L156
- All numbers are correct:
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/primary_only_n_per_cancer_group.tsv
	- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/d8d0f04e017b9ec1b33b88051abdbe9423f95161/analyses/oncoprint-landscape/tables/cancer_group_counts/primary_only/dysembryoplastic-neuroepithelial-tumor_oncoprint_alteration_counts.tsv
