### ISSUE TITLE
Revise Key Resources Table and Resource Availability to ensure compliance with all open science policies

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#462]
- [x] Add Zenodo upload (10.5281/zenodo.7805408) for underlying figure data to Key Resources Table (KRT)
- [x] Update DOI for code following `v1.0.0` release in KRT and **Resource Availability**
- [x] Are KidsFirst accessions sufficient for the **Resource Availability** statement and KRT, or do we need dbGaP identifiers?
- [ ] Is the information in Table S5 sufficient for software key resources?

**Comment by jharenza** [comment]
>Are KidsFirst accessions sufficient for the Resource Availability statement and KRT, or do we need dbGaP identifiers?

I did create a DOI for the exact KF pull for the data, and data are now _only_ available via CBTN and PNOC access request. We are currently in the process of depositing it into dbgap with the X01 data, but not sure when this will be live. We can add the dbgap accession since we do have it: phs002517.v1.p1, but there is no landing page for it yet....
